### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by chadhoang** [DanielArlegui/Learn-Weeb-Language#1]
This code is ass u sure u couldnt make this shit better???

**Comment by DanielArlegui** [comment]
reporting you! my dad works for microsoft kid. My dad went to the navy seals and got over 200 confirmed kills. Better watch out with your words kiddo!

**Comment by chadhoang** [comment]
lmoa

**Comment by DanielArlegui** [comment]
please make sure to give me a better constructive criticism mate

**Comment by DanielArlegui** [comment]
you do not want my grandpa who went to the Vietnam war in 1955 Nov 1st to 360 trickshot no scope your dummy ass
